/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001356",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2e5bff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#b8c3ff",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        "on-tertiary-container": "#bdffdb",
        "inverse-surface": "#2d3133",
        "secondary-container": "#d5e0f8",
        "on-secondary": "#ffffff",
        "on-primary-container": "#efefff",
        "surface-container": "#eceef0",
        "tertiary-fixed-dim": "#4edea3",
        "surface-tint": "#124af0",
        "on-tertiary-fixed-variant": "#005236",
        "surface-bright": "#f7f9fb",
        "surface": "#f7f9fb",
        "on-tertiary-fixed": "#002113",
        "on-surface-variant": "#434656",
        "primary-fixed": "#dde1ff",
        "primary-fixed-dim": "#b8c3ff",
        "secondary-fixed-dim": "#bcc7de",
        "background": "#f7f9fb",
        "outline-variant": "#c4c5d9",
        "on-error-container": "#93000a",
        "on-secondary-container": "#586377",
        "tertiary-container": "#007d55",
        "on-error": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#3c475a",
        "on-primary-fixed-variant": "#0035be",
        "error": "#ba1a1a",
        "primary": "#0040e0",
        "secondary-fixed": "#d8e3fb",
        "on-secondary-fixed": "#111c2d",
        "tertiary-fixed": "#6ffbbe",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "tertiary": "#006242",
        "secondary": "#545f73",
        "outline": "#747688"
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        outfit: ["var(--font-outfit)", "sans-serif"],
        manrope: ["var(--font-manrope)", "sans-serif"],
        amiri: ["var(--font-amiri)", "serif"],
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"]
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
